# docker compose version which is currently 3.8
version: "3.8"

# services : is a list of our container
services:
  mongodb:
    container_name: mongodb
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=database
    restart: always
    ports:
      - "23000:27017"
    volumes:  # our mongodb depends on volume to keep the data alive.
      - data:/data/mongodb

  server:
    container_name: server
    build: ./server
    restart: always
    ports:
      - "24000:8080"
    volumes:
      - ./server:/app
    networks:
      - db
    depends_on:
      - mongodb

  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - "25000:3000"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    networks:
      - db

volumes:
  data:
networks:
  db:
    driver: bridge
  